# Generated by Django 5.1.5 on 2025-01-21 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('number', models.CharField(max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=255)),
                ('obs', models.CharField(max_length=255)),
                ('pavimentation', models.CharField(max_length=255)),
                ('eletricity', models.CharField(max_length=255)),
                ('ilumination', models.CharField(max_length=255)),
                ('quantity_houses', models.CharField(max_length=255)),
                ('photos', models.ImageField(default='report/404.png', upload_to='')),
                ('Reports', models.CharField(blank=True, default='Não há relatórios', max_length=600)),
            ],
        ),
    ]
