# Generated by Django 5.1.5 on 2025-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='obs',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ImageField(default='404.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='unidade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
