# Generated by Django 5.1.5 on 2025-01-27 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_alter_report_obs_alter_report_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=255)),
                ('requerente', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report_fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=255)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('requerente', models.CharField(max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(max_length=25, null=True)),
                ('local', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=255)),
                ('obs', models.CharField(max_length=255)),
                ('eletricity', models.CharField(max_length=255)),
                ('ilumination', models.CharField(max_length=255)),
                ('quantity_houses', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('photos', models.ImageField(default='404.png', upload_to='')),
                ('Reports', models.CharField(blank=True, default='Não há relatórios', max_length=600)),
            ],
        ),
    ]
