# Generated by Django 5.1.5 on 2025-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_certificate_report_fisico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_fisico',
            old_name='obs',
            new_name='pavimentation',
        ),
    ]
