# Generated by Django 5.1.5 on 2025-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_rename_obs_report_fisico_pavimentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='obs',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='unidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
